name: Generate Website

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Generate Website
        env:
          NUXT_APP_BASE_URL: /wahlen/
        run: yarn generate

      - name: Upload generated Website
        uses: actions/upload-artifact@v3
        with:
          name: www.stupa.th-koeln.de
          path: .output/public
